### ISSUE TITLE
`Graphene::Rect#origin=` does not work

### ISSUE THREAD

**Issue by BlobCodes** [hugopl/gtk4.cr#13] opened 2022-03-29 07:50 UTC
Generated code:
```crystal
    def origin=(value : Graphene::Point)
      # Property setter
      _var = (@pointer + 0).as(Pointer(Void)).value = value.to_unsafe
      value
    end
```

Resulting error:
```
Error: no overload matches 'Pointer(Void)#value=' with type Pointer(Void)

Overloads are:
 - Pointer(T)#value=(value : T)
```

**Comment by hugopl** [comment] 2022-03-29 19:49
Yes, the original issue was https://github.com/hugopl/gtk4.cr/issues/9
Fixed on https://github.com/hugopl/gi-crystal/commit/b177dc1f8032d3a1c174873cba13ef373ea60616

For some reason in the commit I added the use case into the libtest but didn't added the Crystal rspec... probably I forgot to `git add` it... :sweat_smile: , the bad side of no code review

**Comment by hugopl** [comment] 2022-03-29 20:01
Interesting... because the current code seems identical to the code proposed as a fix in the original issue, what crystal version are you using?

**Comment by hugopl** [comment] 2022-03-29 20:58
The use case I reproduce in testlib does works, do you have a small code that I can try to compile and see it failing?

**Comment by BlobCodes** [comment] 2022-03-29 20:59
The code from #9 still doesn't work (just tried)

```crystal
require "gtk4"

Graphene::Rect.new(
  origin: Graphene::Point.zero,
  size: Graphene::Size.zero
)
```

**Comment by hugopl** [comment] 2022-03-29 21:38
Got it, in my use case the struct field is a pointer to a struct, but in this use case the struct field is just another struct.

**Comment by hugopl** [comment] 2022-03-29 22:47
Fixed :tada: 

As a bonus, the operator `==` for structs was implemented, i.e. a `LibC.memcmp` call

**Closed by hugopl** 2022-03-29 22:47 UTC
Labels: bug
